services:
  users:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: users
    container_name: users
    restart: always
    ports:
      - ${PORT}:8000
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SERVICE=${POSTGRES_SERVICE}
