# Error codes
UNKNOWN_ERROR = "UNKNOWN_SERVER_ERROR"
USER_EXISTS_ERROR = "EMAIL_ALREDY_USED_ERROR"
DATABASE_ERROR = "DATABASE_ERROR"
LOGIN_ERROR = "INVALID_CREDENTIALS_ERROR"
EXPIRED_TOKEN = "USER_UNAUTHORIZED"
