# Error codes
UNKNOWN_ERROR = "UNKNOWN_SERVER_ERROR"

USER_EXISTS_ERROR = "EMAIL_ALREDY_USED_ERROR"
USER_DOES_NOT_EXISTS_ERROR = "USER_DOES_NOT_EXIST"

DATABASE_ERROR = "DATABASE_ERROR"

LOGIN_ERROR = "INVALID_CREDENTIALS_ERROR"
EXPIRED_TOKEN_ERROR = "USER_UNAUTHORIZED_ERROR"
INVALID_CREDENTIALS_ERROR = "USER_UNAUTHORIZED_ERROR"
INVALID_HEADER_ERROR = "INVALID_HEADER_ERROR"
WRONG_PASSWORD_ERROR = "WRONG_PASSWORD_ERROR"

RECOVERY_NOT_INITIATED_ERROR = "RECOVERY_NOT_INITIATED_ERROR"
INVALID_RECOVERY_CODE_ERROR = "INVALID_RECOVERY_CODE_ERROR"
